<?php

declare(strict_types=1);

/*
Version20260520142444

QUOI : Schéma initial — tables `events` et `users` avec index email unique.

COMMENT : Création complète des colonnes métier (dates, géoloc, images, statuts, soft-delete, indexed).

OÙ : Première migration Doctrine du projet.

POURQUOI : Versionner la structure PostgreSQL avec le code applicatif.
*/

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260520142444 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : tables events et users';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(200) NOT NULL, nom_organisateur VARCHAR(150) NOT NULL, email_contact VARCHAR(180) NOT NULL, prix VARCHAR(60) DEFAULT NULL, categorie VARCHAR(60) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, adresse VARCHAR(255) NOT NULL, ville VARCHAR(120) NOT NULL, code_postal VARCHAR(5) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description TEXT NOT NULL, image_couverture VARCHAR(255) DEFAULT NULL, image_banniere VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, previous_status VARCHAR(20) DEFAULT NULL, moderated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, indexed BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, display_name VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON users (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE users');
    }
}
